### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bwang482** [guillaumegenthial/tf_metrics#6]
Hi there, thanks for the very useful lib. 

As soon as I installed tf_metrics on my azure VM, I started getting the libcublas error for importing tensorflow which never occurred before. What's the installation  requirements for tf_metrics? Is there any caution for installing tf_metrics within a specific environment?

I use tensorflow '1.12.0-rc0' gpu with cuda-9.2

**Comment by Mmva2142** [comment]
When you install tf_metrics, if you use pip install, it will automatically download the requirements as well. 
    On Tuesday, 26 February 2019, 2:30:34 pm GMT+3:30, bluemonk482 <notifications@github.com> wrote:  
 
 
Hi there, thanks for the very useful lib.

As soon as I installed tf_metrics on my azure VM, I started getting the libcublas error for importing tensorflow. What's the installation requirements for tf_metrics?

**Comment by yashkumaratri** [comment]
it is cause of the tf version update, install tf_metrics and then uninstall all tf-gpu and install tf-gpu-1.10 , worked for me
